@extends( 'app' )

@section( 'title', 'AIDDEM' )

@section( 'section-class', 'aiddem' )

@section( 'content' )
            <section class="internal clearfix content bit-1">
                <article class="clearfix bit-1">
                    <h1 class="bit-1">La AIDDEM</h1>
                    <article class="bit-2 clearfix">
                        <p class="bit-1">AIDDEM es una asociación que busca promover la defensa de los médicos a nivel internacional. Contamos con una gran cantidad de firmas de bufetes de abogados en nuestro país y también contamos con la representación en el extranjero, específicamente de Estados Unidos de América, para tener una mayor defensa y soporte internacional; nuestro único afán y compromiso es con la sociedad mexicana y con los médicos de México y del mundo.</p>
                        <p class="bit-1">El artículo 272 y el artículo 81 han sido modificados y entraron en vigor ya publicados en el diario oficial de la federación, están buscando crear un monopolio para la certificación de los especialistas de todo México, únicamente por medio de la asociación civil denominada CONACEM, negando la oportunidad a otras empresas o a otras asociaciones civiles para que puedan defender y agremiarse para hacer la certificación de los médicos, como por ejemplo, como se hace en los famosos boards de certificación en EUA.</p>
                        <p class="bit-1">La CONACEM es una asociación civil; no es una dependencia de gobierno, de ninguna manera la CONACEM es parte de la Dirección General de Profesiones o parte de la Secretaria de Salud, sin embargo con la ley apenas emitida en el DOF se le dieron atribuciones como “auxiliar del gobierno”, pero esto no quiere decir que no deje de ser una asociación civil con dueños y con intereses propios. La CONACEM lleva muchos años cobrando a los médicos, ejerciendo una presión mediática ilegal, ya que exige una certificación cuando todavía sus reglas de operación no estaban vigentes y cuando todavía no estaba claro su manera y su certificación. Esto es totalmente inconstitucional, ya que la colegiación debe ser voluntaria, no obligatoria.</p>
                        <p class="bit-1">Con estas nuevas modificaciones a la ley la CONACEM y el estado, buscan obligar a los médicos de todo México a que se colegien de manera obligatoria, limitando su ejercicio profesional, limitando sus estudios y limitando un derecho que tienen por el 5to constitucional, que es la posibilidad de dedicarse  a lo que ellos quieran siempre y cuando sea licito; la licitud lo da precisamente nuestra cédula profesional la cual no tiene caducidad. Esto pone en un gran predicamento a la dirección general de profesiones, a la cual parece ser que les fueron arrebatados todos y cada uno de sus derechos, porque la supedita la CONACEM en lo que es expedición de cedulas profesionales, ya que para emitir una cedula profesional, tendría  que pedir su visto bueno a la CONACEM.</p>
                        <p class="bit-1">Anteriormente, todas las grandes universidades se habían  amparado,  pero como no estaba vigente el artículo esto no podía surtir efecto. Ahora que ya está vigente este articulo (que de una manera sorpresiva o mañosa, coincidió con el periodo vacacional), creo que los derechos humanos han sido violentados, al tratar de imponernos una limitación a nuestro ejercicio profesional, porque muchos médicos de todas las especialidades del país, que tienen debidamente acreditados su estudios y cuentan con la licitud al tener un título con cedula profesional de médicos especialistas, simple y sencillamente no podrán ejercer si es que no están certificados por la dichosa CONACEM.</p>
                        <p class="bit-1">La CONACEM no ha explicado ni cómo va a actuar, ni cómo va a certificar, ni cuáles son sus criterios, lo cual nos deja en un completo estado de indefensión, lo cual no nos permite de ninguna manera aceptar esto. Los médicos que no se amparen del día de hoy, hasta el día 14 de abril, no podrán  gozar de una suspensión que es parte del juicio de amparo. La suspensión lo que habla y permite, es que mientras dure el juicio de amparo tus derechos no pueden ser violentados, por lo cual no se aplica a ti en ese momento la dichosa ley. Todos y cada uno de los médicos mexicanos debemos actuar en consecuencia de manera rápida y en consecuencia tratar a toda costa, junto con las universidades de México, que de un plumazo no se nos borren tantos años de trabajo, esfuerzo y dedicación. Para todos los que están en este momento, certificados por la CONACEM, yo quiero decirles qué es lo que va a pasar: Cuando cambien la mesa directiva y los criterios no estén claros, pueden haber irregularidades, puede haber sanciones o incluso no aprobarte y esto limitar tu ejercicio profesional hasta que apruebes el método de evaluación, que será el que ellos señalen, como ellos lo señalen.</p>
                    </article>
                    <article class="bit-2 clearfix">
                        {!! Html::image( 'img/aiddem/equipo-de-doctores.jpg', 'Martillo y estetoscopio', [ 'class' => 'bit-1' ] ) !!}
                        <p class="bit-1">No se puede permitir una violación tan grande y tan flagrante de esto, otra pregunta será ¿Y los honorarios por la certificación? Los honorarios que están pidiendo, son las cuotas para certificación ¿En qué van a ser utilizadas? ¿Qué fines van a tener? ¿Hacia dónde se van a dirigir estos recursos? ¿Al gobierno, pregunto, al Estado o a un particular? Creo que es muy grave que hasta el día de hoy, se sigan cobrando precios exorbitantes para una certificación de un médico, donde te obligan a acumular puntos y han sido por años costos exorbitantes cuando ni siquiera estaba en funciones.</p>
                        <p class="bit-1">Nosotros, tenemos la experiencia porque desde el año de 2012, hemos estado combatiendo esta ley, pero es hasta ahora que tenemos los elementos necesarios para llevarlos a juicio. Ya que ya entro en vigencia esta ley, no se podría avanzar más desde el 2012, más que recabar criterios de los jueces, ya que los artículos no estaban vigentes.</p>
                        <p class="bit-1">Yo sé que para muchos médicos esto puede sonar en casualidad, pero está claramente demostrado en el Diario Oficial de la Federación, en el cual se encuentra enumerado en una de las pestañas de esta página de internet, como apenas se le acaba de pedir a la CONACEM que en un máximo de 90 días emita sus reglas de operación. No estaba operando la CONACEM y estaba cobrando los honorarios correspondientes, esto nos lleva muchas suspicacias  y nos lleva a preguntarle a todo el gremio médico. <strong>¿Qué vamos a hacer? La opción es muy sencilla: ¡AMPARARNOS! En un amparo colectivo y en un amparo individual. El amparo individual te permite de una manera directa obtener la suspensión para que mientras dure todo el juicio, tú no seas molestado, ni tengas que certificarte ante la dichosa CONACEM.</strong></p>
                        <p class="bit-1">Los costos de este amparo son sumamente mínimos, ya que tenemos afiliados a cientos de médicos y este amparo además te protege par que te puedas sumar a un amparo colectivo. El amparo colectivo que nosotros tenemos no tiene ningún costo para ti, porque estamos yendo a la Corte Interamericana de Derechos Humanos, para que sea la que sancione al Estado Mexicano por la violación de nuestros derechos humanos.</p>
                        <p class="bit-1">Son temas muy serios, muy fuertes, pero necesarios, para que no permitamos no solamente para nosotros, sino para todas las futuras generaciones de México este atropello, donde se quiere privatizar a los Médicos de México.</p>
                    </article>
            </section>
@stop