@extends( 'app' )

@section( 'title', 'AIDDEM - ¿Quiénes Somos?' )

@section( 'section-class', 'quienes-somos' )

@section( 'content' )
            <section class="internal clearfix content bit-1">
                <article class="clearfix bit-1">
                    {!! Html::image( 'img/quienes-somos/martillo-y-estetoscopio.jpg', 'Martillo y estetoscopio', [ 'class' => 'bit-1' ] ) !!}
                    <h1 class="bit-1">¿Quiénes Somos?</h1>
                    <p class="bit-1">AIDDEM es el resultado de la unión de varios bufetes de abogados y una suma considerable de médicos, que nos hemos dado cuenta del gran daño al que estamos siendo sometidos; este gran daño se llama la privatización del gremio  médico en México. Nos están exigiendo una colegiación obligatoria lo cual es inconstitucional, nos están exigiendo una certificación obligatoria lo cual también  es inconstitucional, porque es una opción  poder estar certificado o no. Lo que mucha gente no puede entender es que si tú no te certificas a partir de esta ley NO PODRAS EJERCER, tan grave como eso es, esta suciendo una privatización de todos los médicos del país donde desde medico más humilde hasta el medico más oneroso, va a tener que pasar un examen de certificación. Parece que ni a los medios de comunicación les interesa este tema, ni a los consejos de profesionistas les interesa este tema, ni los colegios de profesionistas les interesa este tema y no sabemos por qué tal vez porque le da mayor fortaleza a los consejos ya que si no estás certificado por ellos significa que no podrán ejercer.</p>
                    <p class="bit-1">Tal vez sea la causa por la cual nadie se ha pronunciado en este tema , tal vez sea por lo cual esta ley aprovecho las vacaciones de semana santa para que tu no te dieras cuenta y me pregúnto yo ¿Entonces no  los colegios están precisamente para defender a los médicos? Y en estos momento los unicos que quedan desprotegidos son los médicos. Todos conocemos  lo que es una junta de un consejo, la junta de un  colegio; son un grupo, una asociación o son un club el cual toma las decisiones por todos nosotros (a veces inclusive  unilateral),  los cuales tornan y disponen quienes pueden estar, quienes no pueden estar o quienes no deben de estar y queremos señalar que esto afecta a todas las especialidades médicas, ejemplo: ginecología, gastroenterología, cirugía general, etc. incluyendo a los médicos generales.</p>
                    <p class="bit-1">AIDDEM busca proteger todos lo intereses de los médicos de manera individual o de manera colectiva. Individualmente  podemos conseguirte una suspensión de esta ley para que todo este tiempo que dura el amparo, tu no seas molestado y que cuando ganemos este amparo, gracias a dios, definitivamente tu serás de los médicos que gocen de que la  ley no sea aplicada para ti.</p>
                    <p class="bit-1">En cuanto al amparo colectivo significa que cientos de médicos nos estamos reuniendo  en un amparo colectivo, el cual no tiene ningún costo para ti, solo tienes que darle click a esta página de internet, mándarnos tus datos y esperar a que nuestro bufete legal se ponga en contacto contigo,  para que pueda recabar la información que necesitamos de ti: cedula profesional, título, etc.  De esa manera iremos en defensa de todos nuestros  derechos a la corte Interamericana de los Derechos Humanos, para que podamos hacer valer todos nuestros derechos humanos que existen en nuestro país. Esta corte es un organismo mas allá del estado, es un organismo que incluso puede sancionar al estado por hacer una violación tan fragante del estado Mexicano hacia sus habitantes; o sea a todos los mexicanos, ya que este daño no solamente es a todos los medicos mexicanos, no solamente es una monopolización y una privatización de los médicos de México, si no que tambien limita la salud a los mexicanos.</p>
                    {!! Html::image( 'img/quienes-somos/balanza-y-serpiente.png', 'Balanza y serpiente' ) !!}
                    <p class="bit-1">Pregúntense ustedes ¿Qué va a pasar? Hoy en dia en el IMSS, en el ISSTE, y en salubridad no es obligatoria la certificación para los médicos para que puedan ejercer,  todos esos médicos de base  que pertenecen incluso a un sindicato pero, a partir de esta ley tu cedula profesional  va hacer supeditada a lo que la CONACEM diga. La CONACEM es una asociación civil donde no sabemos donde vayan a hacer derivados, los recursos  de los pagos de esas cuotas que están exigiendo. Yo les pediría a todos ustedes qué pensaran ¿Que va a pasar con todos los mexicanos,  si aun asi en este momento, no podemos  al cien por ciento tener acceso al servicio de salud de especialistas?  ¿Que va a pasar si entonces queda reducido el número de especialistas, por que no se pueden certificar? Creo que esta por formarse un problema  de salud pública como nunca lo ha tenido México.  Hacemos un llamado a través de este medio al presidente de México, el Licenciado Enrique Peña Nieto, para que de la instrucciones correspondientes para que este articulo 272 y artículo 81, sean derogados, para que estas reglas de operación sean analizadas y sean derogadas ; para que se le exija a la secretaria de salud,  que no violente los derechos de todos los mexicanos y que esta atribuciones,  están muy  claras: Son de la dirección  general de profesiones.</p>
                    <p class="bit-1">Quiero  comentar  que la dirección  general de profesiones, si tiene la capacidad  y la infraestructura para dar seguimiento  a todos los médicos de México. Pero la CONACEM en este momento  no las tiene; no sabemos si va a recibir un subsidio,  no sabemos si va recibir recursos  de nuestro país, no veo por qué dárselos  a una asociación de particulares ¿Por que no fortalecer nuestras instituciones?</p>
                    <p class="bit-1">No estamos en contra de la certificación, estamos a favor de las certificaciones, pero según la ley  los que tienen esa atribución según la Dirección General  de Profesiones,  son los colegios de profesionistas e   inclusive, los consejos no están dentro de los organismos que tienen considerado  la dirección general de profesiones para hacer estas certificaciones. ¡Ya basta de que se esté lucrando con una certificación desde hace años! Que definitivamente debe ser un gran negocio y a todos los médicos que llevan años pagando esta certificación les comento: Revisen si estás certificaciones de la CONACEM  están registradas ante la dirección general de profesiones, revisen que según el Diario Oficial de la Federación apenas va a emitir sus reglas de operación, por lo tanto ni siquiera estaba operando. Defiéndanse de lo que puede ser  no solamente para ustedes, para sus hijos y todas las futuras generaciones de México, un daño irreparable…se llama la privatización de los Servicios Médicos de México.</p>
            </section>
@stop